BIOSTOOLSROOT=$(shell pwd)/sources
TMS470CGTOOLPATH=$(BIOSTOOLSROOT)/cgt
CODECS_INSTALL_DIR=$(BIOSTOOLSROOT)/codecs
BIOS_INSTALL_DIR=$(BIOSTOOLSROOT)/bios
RPMSG_INSTALL_DIR=$(BIOSTOOLSROOT)/rpmsg
XDC_INSTALL_DIR=$(BIOSTOOLSROOT)/xdc
IPC_INSTALL_DIR=$(BIOSTOOLSROOT)/ipc
FC_INSTALL_DIR=$(BIOSTOOLSROOT)/fc
XDAIS_INSTALL_DIR=$(BIOSTOOLSROOT)/xdais
CE_INSTALL_DIR=$(BIOSTOOLSROOT)/ce
OSAL_INSTALL_DIR=$(BIOSTOOLSROOT)/osal
IPUMM_INSTALL_DIR=$(BIOSTOOLSROOT)/ipumm

IPUMM_CONF = TMS470CGTOOLPATH=$(TMS470CGTOOLPATH) \
	BIOSTOOLSROOT=$(BIOSTOOLSROOT) \
	BIOSVERSION=bios \
	CEVERSION=ce \
	XDAISVERSION=xdais \
	FCVERSION=fc \
	IPCVERSION=ipc \
	XDCVERSION=xdc \
	RPMSGSRC=${RPMSG_INSTALL_DIR} \
	IPCSRC=${IPC_INSTALL_DIR} \
	CODECSPATH=$(CODECS_INSTALL_DIR) \
	TRACELEVEL=0

RPMSG_CONF = TMS470CGTOOLPATH=$(TMS470CGTOOLPATH) \
	BIOSTOOLSROOT=$(BIOSTOOLSROOT) \
	XDCVERSION=xdc \
	BIOSVERSION=bios \
	IPCVERSION=ipc

IPC_CONF = TMS470CGTOOLPATH=$(TMS470CGTOOLPATH) \
	BIOS_INSTALL_DIR=$(BIOS_INSTALL_DIR) \
	XDC_INSTALL_DIR=$(XDC_INSTALL_DIR)

FC_CONF = TMS470CGTOOLPATH=$(TMS470CGTOOLPATH) \
	BIOS_INSTALL_DIR=$(BIOS_INSTALL_DIR) \
	XDAIS_INSTALL_DIR=$(XDAIS_INSTALL_DIR) \
	XDC_INSTALL_DIR=$(XDC_INSTALL_DIR)

XDAIS_CONF = TMS470CGTOOLPATH=$(TMS470CGTOOLPATH) \
	BIOS_INSTALL_DIR=$(BIOS_INSTALL_DIR) \
	XDC_INSTALL_DIR=$(XDC_INSTALL_DIR) \

OSAL_CONF = TMS470CGTOOLPATH=$(TMS470CGTOOLPATH) \
	BIOS_INSTALL_DIR=$(BIOS_INSTALL_DIR) \
	XDC_INSTALL_DIR=$(XDC_INSTALL_DIR)

CE_CONF = TMS470CGTOOLPATH=$(TMS470CGTOOLPATH) \
	BIOS_INSTALL_DIR=$(BIOS_INSTALL_DIR) \
	XDAIS_INSTALL_DIR=$(XDAIS_INSTALL_DIR) \
	IPC_INSTALL_DIR=$(IPC_INSTALL_DIR) \
	FC_INSTALL_DIR=$(FC_INSTALL_DIR) \
	CE_INSTALL_DIR=$(CE_INSTALL_DIR) \
	OSAL_INSTALL_DIR=$(OSAL_INSTALL_DIR) \
	XDC_INSTALL_DIR=$(XDC_INSTALL_DIR)

BIOS_CONF = TMS470CGTOOLPATH=$(TMS470CGTOOLPATH) \
	XDC_INSTALL_DIR=$(XDC_INSTALL_DIR)
